version: "3.8"

services:
  belajar-user-role:
    image: postgres:16.0
    container_name: belajar-user-role
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rahasia
